#!/usr/bin/env python2.7
#
#  crapshoot - testing driver management
#
#  Copyright 2017 Ikey Doherty <ikey@solus-project.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#

from doflicky.driver.nvidia import DriverBundleNvidia
from doflicky.driver.nvidia import DriverBundleNvidia304
from doflicky.driver.nvidia import DriverBundleNvidia340

class BundleSet:

    drivers = None
    allDrivers = None
    uniqueDrivers = None

    def __init__(self):
        """ Initialise the potential driver bundle set """
        self.drivers = [
            DriverBundleNvidia304(),
            DriverBundleNvidia340(),
            DriverBundleNvidia(),
        ]
        self.allDrivers = list()
        self.uniqueDrivers = list()

    def detect(self):
        """ Perform main detection routine """
        for driver in self.drivers:
            if driver.is_present():
                self.add_driver(driver)

    def add_driver(self, driver):
        """ Attempt to add a driver to the set and avoid conflicts """
        base = driver.get_base()
        self.allDrivers.append(driver)
        if base is not None:
            otherDrivers = [x for x in self.uniqueDrivers if x.get_base() == base]

            for existing in otherDrivers:
                if existing.get_priority() > driver:
                    print("DEBUG: {} shadowed by existing {}".format(
                        driver.get_name(), existing.get_name()))
                    return
                elif driver.get_priority() > existing.get_priority():
                    self.uniqueDrivers.remove(existing)
                    self.uniqueDrivers.append(driver)

            if len(otherDrivers) < 1:
                self.uniqueDrivers.append(driver)
        else:
            self.uniqueDrivers.append(driver)

if __name__ == "__main__":

    bs = BundleSet()
    bs.detect()

    for driver in bs.uniqueDrivers:
        print("Found supported hardware: %s" % driver.get_name())
        print("Packages: %s" % ", ".join(driver.get_packages(False)))
        print("Packages+32: %s" % ", ".join(driver.get_packages(True)))
